baseURL = 'https://blog.heehoposting.xyz'
languageCode = 'en-us'
title = "Jackson Frost's Tavern"
theme = 'terminal'
pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false


[languages]
  [languages.en]
    languageName = "English"
    title = "Jackson Frost's Tavern"

  [languages.en.params]
    subtitle = "A simple, retro theme for Hugo"
    owner = "hackisonjd"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Jackson Frost's Tavern"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "back-to-heehoposting"
        name = "Go Back to Heehoposting"
        url = "https://heehoposting.xyz"
